#!/bin/sh
#
# Copyright (c) 2008 Citrix Systems, Inc.
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#

TYPE=`echo ${XENBUS_PATH} | cut -f 2 -d '/'`
DOMID=`echo ${XENBUS_PATH} | cut -f 3 -d '/'`
DEVID=`echo ${XENBUS_PATH} | cut -f 4 -d '/'`

XAPI=/xapi/${DOMID}/hotplug/${TYPE}/${DEVID}

case "$1" in
add)
    PARAMS=$(xenstore-read "${XENBUS_PATH}/params")
    MINOR=$(stat -c '%T' ${PARAMS})
    xenstore-write "${XENBUS_PATH}/physical-device" "fe:${MINOR}"
    xenstore-write "${XENBUS_PATH}/physical-device-path" "${PARAMS}"

    xenstore-watch -n 2 "${XENBUS_PATH}/state" 2>/dev/null &
    watch_pid=$!
    xenbus_state=$(xenstore-read "${XENBUS_PATH}/state" 2>/dev/null || echo "unknown")
    if [ "$xenbus_state" == "1" ] ; then
        wait $watch_pid
        xenbus_state=$(xenstore-read "${XENBUS_PATH}/state" 2>/dev/null || echo "unknown")
    fi
    if [ "$xenbus_state" != "2" ] ; then
        echo "FATAL: ${XENBUS_PATH}/state : $xenbus_state"
        exit 1
    fi

    xenstore-write "${XAPI}/hotplug" "online"
    ;;

remove)
    xenstore-rm "/xapi/${DOMID}"
    ;;
esac
